name: Generator ci

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 2 * * 1-5'

jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.data.outputs.version }}

    steps:
      - name: Download Gecko
        run: |
          wget -O mozilla.tar.xz https://moz-latest-release.gluon.dev/source/stable
          mkdir -p mozilla
          tar --strip-components=1 -xf ./mozilla.tar.xz -C ./mozilla

      - name: Set gecko version
        run: |
          echo "version=$(cat mozilla/browser/config/version.txt)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          path: index

      - name: Generate Namespaces
        run: |
          cd index
          npm i
          npm run namespaces ../mozilla

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate namespaces for `${{ steps.data.outputs.version }}`
          repository: index

      - name: Generate ESM
        run: |
          cd index
          npm run esm ../mozilla

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate ESM for `${{ steps.data.outputs.version }}`
          repository: index

      - name: Generate Interfaces
        run: |
          cd index
          npm run interfaces ../mozilla

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate interfaces for `${{ steps.data.outputs.version }}`
          repository: index

      - name: Generate XUL elements index
        run: |
          cd index
          npm run xulElements ../mozilla

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate interfaces for `${{ steps.data.outputs.version }}`
          repository: index

      - name: Generate mozbuild index
        run: |
          cd index
          npm run mozbuild ../mozilla

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate mozbuild for `${{ steps.data.outputs.version }}`
          repository: index
