name: Generator ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: |
        hg clone https://hg.mozilla.org/releases/mozilla-release mozilla-release
    
    - uses: actions/checkout@v3
      with:
        path: index
    
    - name: Run
      run: |
        npm i 
        npm run generate ../mozilla-release
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Geneate files
        repository: index
