name: Generator ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Gecko
        run: |
          wget -O mozilla.tar.xz https://moz-latest-release.gluon.dev/source/stable
          mkdir -p mozilla
          tar --strip-components=1 -xf ./mozilla.tar.xz -C ./mozilla

      - uses: actions/checkout@v3
        with:
          path: index

      - name: Install JSDoc
        run: |
          npm i -g jsdoc

      - name: Run
        run: |
          cd index
          npm i
          npm run namespaces ../mozilla
          npm run legacyModules ../mozilla

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate files
          repository: index
